package com.pojo;

import org.hibernate.validator.constraints.Email;

import javax.validation.constraints.Pattern;
import java.io.Serializable;

public class Employee implements Serializable {


    public Employee() {
    }



    public Employee(Integer empId, String empName, Byte gender, String email, Integer dId) {

        this.empId = empId;
        this.empName = empName;
        this.gender = gender;
        this.email = email;
        this.dId = dId;
    }


    @Override
    public String toString() {
        return "Employee{" +
                "empId=" + empId +
                ", empName='" + empName + '\'' +
                ", gender=" + gender +
                ", email='" + email + '\'' +
                ", dId=" + dId +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_emp.emp_id
     *
     * @mbggenerated Sun Apr 17 16:50:33 CST 2022
     */
    private Integer empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_emp.emp_name
     *
     * @mbggenerated Sun Apr 17 16:50:33 CST 2022
     */
    @Pattern(regexp="^[\u2E80-\u9FFF]{2,5}"
            ,message=" 学生姓名必须是2-5位汉字 ")
    private String empName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_emp.gender
     *
     * @mbggenerated Sun Apr 17 16:50:33 CST 2022
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_emp.email
     *
     * @mbggenerated Sun Apr 17 16:50:33 CST 2022
     */
    @Email(message = "邮箱格式不正确")
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_emp.d_id
     *
     * @mbggenerated Sun Apr 17 16:50:33 CST 2022
     */
    private Integer dId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_emp.d_id
     *
     * @mbggenerated Sun Apr 17 16:50:33 CST 2022
     */
    private Department department;

    public Department getDepartment() {
        return department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_emp.emp_id
     *
     * @return the value of tb_emp.emp_id
     *
     * @mbggenerated Sun Apr 17 16:50:33 CST 2022
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_emp.emp_id
     *
     * @param empId the value for tb_emp.emp_id
     *
     * @mbggenerated Sun Apr 17 16:50:33 CST 2022
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_emp.emp_name
     *
     * @return the value of tb_emp.emp_name
     *
     * @mbggenerated Sun Apr 17 16:50:33 CST 2022
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_emp.emp_name
     *
     * @param empName the value for tb_emp.emp_name
     *
     * @mbggenerated Sun Apr 17 16:50:33 CST 2022
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_emp.gender
     *
     * @return the value of tb_emp.gender
     *
     * @mbggenerated Sun Apr 17 16:50:33 CST 2022
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_emp.gender
     *
     * @param gender the value for tb_emp.gender
     *
     * @mbggenerated Sun Apr 17 16:50:33 CST 2022
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_emp.email
     *
     * @return the value of tb_emp.email
     *
     * @mbggenerated Sun Apr 17 16:50:33 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_emp.email
     *
     * @param email the value for tb_emp.email
     *
     * @mbggenerated Sun Apr 17 16:50:33 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_emp.d_id
     *
     * @return the value of tb_emp.d_id
     *
     * @mbggenerated Sun Apr 17 16:50:33 CST 2022
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_emp.d_id
     *
     * @param dId the value for tb_emp.d_id
     *
     * @mbggenerated Sun Apr 17 16:50:33 CST 2022
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }
}