package com.dao;

import com.pojo.Employee;
import com.pojo.EmployeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeeMapper {



    /** 查询满足example条件的员工, 包括所属部门信息 */
    List<Employee> queryByExampleWithDept(EmployeeExample example);

    /** 根据员工id查询员工, 包括所属部门信息 */
    Employee queryByIdWithDept(int empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_emp
     *
     * @mbggenerated Sun Apr 17 16:50:33 CST 2022
     */
    int countByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_emp
     *
     * @mbggenerated Sun Apr 17 16:50:33 CST 2022
     */
    int deleteByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_emp
     *
     * @mbggenerated Sun Apr 17 16:50:33 CST 2022
     */
    int deleteByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_emp
     *
     * @mbggenerated Sun Apr 17 16:50:33 CST 2022
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_emp
     *
     * @mbggenerated Sun Apr 17 16:50:33 CST 2022
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_emp
     *
     * @mbggenerated Sun Apr 17 16:50:33 CST 2022
     */
    List<Employee> selectByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_emp
     *
     * @mbggenerated Sun Apr 17 16:50:33 CST 2022
     */
    Employee selectByPrimaryKey(Integer empId);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_emp
     *
     * @mbggenerated Sun Apr 17 16:50:33 CST 2022
     */
    List<Employee> selectByExampleWithDept(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_emp
     *
     * @mbggenerated Sun Apr 17 16:50:33 CST 2022
     */
    Employee selectByPrimaryKeyWithDept(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_emp
     *
     * @mbggenerated Sun Apr 17 16:50:33 CST 2022
     */
    int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_emp
     *
     * @mbggenerated Sun Apr 17 16:50:33 CST 2022
     */
    int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_emp
     *
     * @mbggenerated Sun Apr 17 16:50:33 CST 2022
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_emp
     *
     * @mbggenerated Sun Apr 17 16:50:33 CST 2022
     */
    int updateByPrimaryKey(Employee record);
}